apiVersion: digitalis.io/v1
kind: ValsSecret
metadata:
  name: vals-secret-sample
  labels:
    environment: demo
    project: demo
spec:
  name: my-secret
  ttl: 3600
  type: Opaque
  data:
    username:
      ref: ref+gcpsecrets://<GCP_PROJECT_NAME>/my-secure-user?version=1
      encoding: text
    password:
      ref: ref+gcpsecrets://<GCP_PROJECT_NAME>/my-secure-secret?version=1
      encoding: text