apiVersion: v1
kind: Pod
metadata:
  labels:
    run: secret-pod
  name: secret-pod
spec:
  containers:
  - args:
    - sh
    - -c
    - sleep 5d
    image: busybox:1.31.1
    name: secret-pod
    env:
    - name: APP_SECURE_USER
    - name: APP_SECURE_SECRET
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always